/** Clued word lists for the mini crossword. Kept small and common so the
 *  app stays offline-tiny; the generator fills a 5×5 grid from these. */

export type Entry = [word: string, clue: string];

export const WORDS3: readonly Entry[] = [
  ["ace", "Top card, or a served winner"],
  ["act", "Part of a play"],
  ["add", "Sum up"],
  ["age", "Candles on the cake count it"],
  ["ago", "In the past"],
  ["aid", "Help"],
  ["aim", "Target"],
  ["air", "What we breathe"],
  ["ale", "Pub pint"],
  ["ant", "Picnic invader"],
  ["ape", "Gorilla, e.g."],
  ["arc", "Part of a circle"],
  ["arm", "Elbow's limb"],
  ["art", "Gallery display"],
  ["ash", "Fireplace leftover"],
  ["ate", "Had dinner"],
  ["awe", "Wonder"],
  ["axe", "Wood chopper"],
  ["bad", "Not good"],
  ["bag", "Grocery carrier"],
  ["ban", "Forbid"],
  ["bar", "Chocolate unit"],
  ["bat", "Cave flier"],
  ["bed", "Place to sleep"],
  ["bee", "Honey maker"],
  ["big", "Large"],
  ["bit", "Small piece"],
  ["boa", "Feathery scarf"],
  ["bow", "Arrow launcher"],
  ["box", "Cardboard container"],
  ["bud", "Flower-to-be"],
  ["bus", "School transport"],
  ["cab", "Taxi"],
  ["can", "Tin container"],
  ["cap", "Bottle top"],
  ["car", "Garage occupant"],
  ["cat", "Whiskered pet"],
  ["cow", "Farm moo-er"],
  ["cry", "Shed tears"],
  ["cub", "Bear baby"],
  ["cup", "Tea holder"],
  ["cut", "Trim"],
  ["dam", "River blocker"],
  ["day", "24 hours"],
  ["den", "Lion's home"],
  ["dew", "Morning grass drops"],
  ["dig", "Use a shovel"],
  ["dot", "Tiny mark"],
  ["dry", "Not wet"],
  ["due", "Expected"],
  ["ear", "Hearing organ"],
  ["eat", "Have a meal"],
  ["eel", "Slippery fish"],
  ["egg", "Omelette base"],
  ["ego", "Sense of self"],
  ["elf", "Santa's helper"],
  ["elm", "Shade tree"],
  ["end", "Finish"],
  ["era", "Historical period"],
  ["eve", "Night before"],
  ["eye", "Seeing organ"],
  ["fan", "Cooling spinner"],
  ["far", "Not near"],
  ["fee", "Charge"],
  ["few", "Not many"],
  ["fig", "Newton fruit"],
  ["fin", "Shark's blade"],
  ["fit", "In shape"],
  ["fix", "Repair"],
  ["fly", "Buzzing pest"],
  ["fog", "Thick mist"],
  ["fox", "Sly animal"],
  ["fun", "Good time"],
  ["gap", "Opening"],
  ["gas", "Fuel at the pump"],
  ["gem", "Precious stone"],
  ["get", "Receive"],
  ["gum", "Chewy stick"],
  ["gut", "Belly"],
  ["ham", "Sandwich meat"],
  ["hat", "Head topper"],
  ["hay", "Barn bale"],
  ["hen", "Egg layer"],
  ["hip", "Trendy"],
  ["hit", "Chart topper"],
  ["hop", "Bunny's move"],
  ["hot", "Scalding"],
  ["hub", "Wheel center"],
  ["hue", "Shade of colour"],
  ["hug", "Warm embrace"],
  ["ice", "Rink surface"],
  ["ink", "Pen filler"],
  ["inn", "Roadside lodging"],
  ["ion", "Charged atom"],
  ["ivy", "Climbing vine"],
  ["jam", "Toast spread"],
  ["jar", "Pickle container"],
  ["jet", "Fast plane"],
  ["jog", "Slow run"],
  ["key", "Lock opener"],
  ["kit", "Set of tools"],
  ["lap", "Racetrack circuit"],
  ["law", "Rule of the land"],
  ["leg", "Knee's limb"],
  ["let", "Allow"],
  ["lid", "Jar topper"],
  ["lie", "Untruth"],
  ["lip", "Kiss planter"],
  ["log", "Fireplace fuel"],
  ["low", "Not high"],
  ["map", "Treasure hunter's guide"],
  ["mat", "Doorstep rug"],
  ["mix", "Stir together"],
  ["mop", "Floor cleaner"],
  ["mud", "Puddle goo"],
  ["mug", "Coffee cup"],
  ["nap", "Short sleep"],
  ["net", "Goal fabric"],
  ["new", "Fresh"],
  ["nod", "Silent yes"],
  ["now", "At this moment"],
  ["nut", "Squirrel's stash"],
  ["oak", "Acorn tree"],
  ["oar", "Rowboat paddle"],
  ["odd", "Strange"],
  ["oil", "Engine lubricant"],
  ["old", "Aged"],
  ["one", "Single"],
  ["orb", "Sphere"],
  ["ore", "Mined rock"],
  ["owl", "Night hooter"],
  ["own", "Possess"],
  ["pan", "Frying vessel"],
  ["paw", "Dog's foot"],
  ["pea", "Little green veggie"],
  ["pen", "Ink stick"],
  ["pet", "Family animal"],
  ["pie", "Dessert with a crust"],
  ["pig", "Farm oinker"],
  ["pin", "Bowling target"],
  ["pit", "Peach center"],
  ["pot", "Stew vessel"],
  ["pun", "Wordplay joke"],
  ["rag", "Cleaning cloth"],
  ["ram", "Male sheep"],
  ["rat", "Sewer rodent"],
  ["raw", "Uncooked"],
  ["ray", "Beam of light"],
  ["red", "Stop-light colour"],
  ["rib", "Chest bone"],
  ["rim", "Basketball hoop edge"],
  ["rip", "Tear"],
  ["rot", "Decay"],
  ["row", "Line of seats"],
  ["rug", "Floor cover"],
  ["run", "Sprint"],
  ["rye", "Bread grain"],
  ["sad", "Blue"],
  ["saw", "Toothed cutter"],
  ["sea", "Salty expanse"],
  ["see", "Spot"],
  ["set", "Tennis unit"],
  ["sew", "Stitch"],
  ["shy", "Timid"],
  ["sip", "Small drink"],
  ["sit", "Take a seat"],
  ["six", "Half a dozen"],
  ["ski", "Slope glider"],
  ["sky", "Cloud's home"],
  ["son", "Male heir"],
  ["spa", "Pampering place"],
  ["spy", "Secret agent"],
  ["sum", "Addition result"],
  ["sun", "Day star"],
  ["tan", "Beach souvenir"],
  ["tap", "Faucet"],
  ["tar", "Road black"],
  ["tax", "April payment"],
  ["tea", "Leafy brew"],
  ["ten", "Perfect score"],
  ["tie", "Suit accessory"],
  ["tin", "Can metal"],
  ["tip", "Waiter's bonus"],
  ["toe", "Sock filler"],
  ["ton", "Heavy weight"],
  ["top", "Spinning toy"],
  ["toy", "Playroom item"],
  ["try", "Attempt"],
  ["tub", "Bath vessel"],
  ["two", "Pair count"],
  ["urn", "Fancy vase"],
  ["use", "Employ"],
  ["van", "Delivery vehicle"],
  ["vet", "Animal doctor"],
  ["war", "Peace's opposite"],
  ["wax", "Candle stuff"],
  ["web", "Spider's work"],
  ["wet", "Soaked"],
  ["wig", "Fake hair"],
  ["win", "Come first"],
  ["yak", "Shaggy ox"],
  ["yam", "Sweet potato kin"],
  ["yes", "Affirmative"],
  ["zoo", "Animal park"]
];

export const WORDS4: readonly Entry[] = [
  ["able", "Capable"],
  ["acid", "Lemon juice quality"],
  ["acre", "Farm measure"],
  ["aged", "Like fine wine"],
  ["also", "Too"],
  ["area", "Region"],
  ["army", "Soldiers en masse"],
  ["atom", "Tiny building block"],
  ["aunt", "Parent's sister"],
  ["auto", "Car"],
  ["away", "Not home"],
  ["baby", "Newest family member"],
  ["back", "Rear"],
  ["bake", "Make bread"],
  ["ball", "Round toy"],
  ["band", "Touring musicians"],
  ["bank", "Money house"],
  ["barn", "Hay storage"],
  ["base", "Foundation"],
  ["bath", "Tub soak"],
  ["beam", "Ray of light"],
  ["bean", "Chili morsel"],
  ["bear", "Honey lover"],
  ["bell", "School ringer"],
  ["belt", "Waist strap"],
  ["bend", "Curve"],
  ["bird", "Nest builder"],
  ["blue", "Sky colour"],
  ["boat", "Water vessel"],
  ["bone", "Dog's treasure"],
  ["book", "Library item"],
  ["boot", "Winter footwear"],
  ["born", "Brought into the world"],
  ["both", "The two of them"],
  ["bowl", "Cereal holder"],
  ["bulb", "Lamp part"],
  ["burn", "Campfire hazard"],
  ["bush", "Garden shrub"],
  ["cage", "Bird enclosure"],
  ["cake", "Birthday centerpiece"],
  ["calm", "Peaceful"],
  ["camp", "Summer tents"],
  ["card", "Deck unit"],
  ["care", "Look after"],
  ["cash", "Paper money"],
  ["cave", "Bat home"],
  ["cell", "Body unit"],
  ["chef", "Kitchen boss"],
  ["city", "Urban area"],
  ["clay", "Potter's medium"],
  ["clip", "Paper fastener"],
  ["club", "Golf stick"],
  ["coal", "Old fuel"],
  ["coat", "Winter layer"],
  ["code", "Programmer's product"],
  ["coin", "Pocket change"],
  ["cold", "Winter feeling"],
  ["cook", "Prepare a meal"],
  ["cool", "Slightly cold"],
  ["core", "Apple center"],
  ["corn", "Cob crop"],
  ["cost", "Price"],
  ["crab", "Sideways walker"],
  ["crew", "Ship staff"],
  ["crow", "Black bird"],
  ["cube", "Sugar shape"],
  ["dark", "Without light"],
  ["dawn", "Daybreak"],
  ["dear", "Letter opener"],
  ["deep", "Far down"],
  ["deer", "Forest grazer"],
  ["desk", "Office surface"],
  ["dish", "Plate"],
  ["dive", "Pool plunge"],
  ["dock", "Boat parking"],
  ["door", "Room entrance"],
  ["down", "Not up"],
  ["draw", "Sketch"],
  ["drum", "Beat keeper"],
  ["duck", "Pond quacker"],
  ["dust", "Shelf coating"],
  ["each", "Apiece"],
  ["earn", "Bring home"],
  ["east", "Sunrise direction"],
  ["easy", "Simple"],
  ["echo", "Canyon reply"],
  ["edge", "Border"],
  ["else", "Otherwise"],
  ["even", "Divisible by two"],
  ["exam", "Final test"],
  ["exit", "Way out"],
  ["face", "Clock front"],
  ["fact", "True statement"],
  ["farm", "Tractor's home"],
  ["fast", "Quick"],
  ["fear", "Dread"],
  ["fern", "Shade plant"],
  ["fire", "Camp glow"],
  ["fish", "Aquarium dweller"],
  ["five", "Basketball squad"],
  ["flag", "Pole flyer"],
  ["flat", "Pancake-like"],
  ["flow", "River motion"],
  ["food", "Fuel for people"],
  ["foot", "Twelve inches"],
  ["fork", "Salad utensil"],
  ["fort", "Pillow construction"],
  ["four", "Square's sides"],
  ["free", "Costing nothing"],
  ["frog", "Lily pad sitter"],
  ["game", "Playtime activity"],
  ["gate", "Fence door"],
  ["gift", "Wrapped surprise"],
  ["glow", "Ember light"],
  ["goal", "Soccer target"],
  ["goat", "Mountain climber"],
  ["gold", "First-place metal"],
  ["gone", "No longer here"],
  ["good", "Well done"],
  ["gray", "Cloudy-day colour"],
  ["grow", "Get bigger"],
  ["hair", "Barber's material"],
  ["half", "Fifty percent"],
  ["hall", "Corridor"],
  ["hand", "Clock pointer"],
  ["hard", "Not soft"],
  ["harp", "Angel's instrument"],
  ["heat", "Summer wave"],
  ["herb", "Basil, e.g."],
  ["hero", "Cape wearer"],
  ["high", "Way up"],
  ["hill", "Small mountain"],
  ["hive", "Bee house"],
  ["hole", "Golf target"],
  ["home", "Where the heart is"],
  ["hope", "Optimist's fuel"],
  ["horn", "Rhino feature"],
  ["hour", "Sixty minutes"],
  ["huge", "Enormous"],
  ["icon", "Desktop clickable"],
  ["idea", "Light-bulb moment"],
  ["inch", "Small measure"],
  ["iron", "Wrinkle fighter"],
  ["item", "List entry"],
  ["join", "Connect"],
  ["jump", "Leave the ground"],
  ["keep", "Hold on to"],
  ["kind", "Considerate"],
  ["king", "Chess target"],
  ["kite", "Windy-day flier"],
  ["knee", "Leg joint"],
  ["knot", "Rope tangle"],
  ["lake", "Inland water"],
  ["lamb", "Young sheep"],
  ["lamp", "Desk light"],
  ["land", "Touch down"],
  ["lane", "Bowling strip"],
  ["last", "Final"],
  ["late", "After the bell"],
  ["lawn", "Mowed green"],
  ["leaf", "Autumn faller"],
  ["lean", "Tilt"],
  ["left", "Port side"],
  ["lend", "Loan out"],
  ["life", "Biography subject"],
  ["lift", "Elevate"],
  ["lime", "Green citrus"],
  ["line", "Queue"],
  ["lion", "Savanna king"],
  ["list", "To-do sheet"],
  ["long", "Not short"],
  ["loud", "Hard to ignore"],
  ["love", "Valentine feeling"],
  ["luck", "Four-leaf clover gift"],
  ["made", "Manufactured"],
  ["mail", "Letters and parcels"],
  ["main", "Primary"],
  ["make", "Create"],
  ["many", "A lot of"],
  ["mask", "Costume face"],
  ["maze", "Puzzle of paths"],
  ["meal", "Breakfast or dinner"],
  ["melt", "Turn to liquid"],
  ["menu", "Diner's reading"],
  ["mice", "Cheese fans"],
  ["mild", "Gentle"],
  ["mile", "5280 feet"],
  ["milk", "Cereal partner"],
  ["mint", "Fresh-breath herb"],
  ["moon", "Night light"],
  ["more", "Additional"],
  ["moss", "Soft forest carpet"],
  ["moth", "Porch-light circler"],
  ["move", "Change place"],
  ["much", "A great deal"],
  ["name", "What you're called"],
  ["near", "Close by"],
  ["neat", "Tidy"],
  ["neck", "Giraffe's pride"],
  ["nest", "Egg cradle"],
  ["news", "Daily headlines"],
  ["next", "Following"],
  ["nice", "Pleasant"],
  ["nine", "Baseball team count"],
  ["none", "Zero"],
  ["noon", "Midday"],
  ["nose", "Scent detector"],
  ["note", "Musical unit"],
  ["oath", "Solemn promise"],
  ["obey", "Follow orders"],
  ["once", "One time"],
  ["only", "Sole"],
  ["open", "Not shut"],
  ["oval", "Egg shape"],
  ["oven", "Baker's chamber"],
  ["over", "Above"],
  ["pace", "Walking speed"],
  ["page", "Book leaf"],
  ["pair", "Two of a kind"],
  ["palm", "Beach tree"],
  ["park", "Picnic spot"],
  ["part", "Piece"],
  ["past", "History"],
  ["path", "Garden walkway"],
  ["pear", "Bell-shaped fruit"],
  ["pile", "Heap"],
  ["pine", "Needle tree"],
  ["pink", "Flamingo colour"],
  ["plan", "Blueprint"],
  ["play", "Stage show"],
  ["plum", "Purple fruit"],
  ["plus", "Addition sign"],
  ["pond", "Duck's water"],
  ["pony", "Small horse"],
  ["pool", "Backyard swim spot"],
  ["port", "Ship's stop"],
  ["post", "Mail, in Britain"],
  ["pump", "Tire inflator"],
  ["pure", "Unmixed"],
  ["push", "Shove"],
  ["race", "Speed contest"],
  ["rain", "Umbrella weather"],
  ["ramp", "Skateboard slope"],
  ["rare", "Hard to find"],
  ["rate", "Speed measure"],
  ["read", "Enjoy a book"],
  ["real", "Genuine"],
  ["rent", "Monthly payment"],
  ["rest", "Take a break"],
  ["rice", "Sushi grain"],
  ["rich", "Wealthy"],
  ["ride", "Carousel turn"],
  ["ring", "Finger circle"],
  ["rise", "Go up"],
  ["road", "Car's path"],
  ["rock", "Guitar genre"],
  ["role", "Actor's part"],
  ["roof", "House topper"],
  ["room", "House division"],
  ["root", "Plant anchor"],
  ["rope", "Climber's line"],
  ["rose", "Thorny flower"],
  ["ruby", "Red gem"],
  ["rule", "Regulation"],
  ["rush", "Hurry"],
  ["safe", "Vault"],
  ["sail", "Catch the wind"],
  ["salt", "Pepper's partner"],
  ["sand", "Beach grains"],
  ["seat", "Place to sit"],
  ["seed", "Garden starter"],
  ["shoe", "Lace-up wear"],
  ["show", "TV program"],
  ["side", "Team to root for"],
  ["sign", "Stop ___"],
  ["silk", "Smooth fabric"],
  ["sing", "Use your voice"],
  ["site", "Web address"],
  ["size", "Small, medium, or large"],
  ["skin", "Body cover"],
  ["slow", "Snail-paced"],
  ["snow", "Winter blanket"],
  ["sock", "Shoe liner"],
  ["sofa", "Living-room seat"],
  ["soft", "Pillow-like"],
  ["soil", "Garden dirt"],
  ["song", "Radio play"],
  ["soon", "Before long"],
  ["soup", "Spoon meal"],
  ["spin", "Twirl"],
  ["spot", "Dalmatian mark"],
  ["star", "Night twinkler"],
  ["stay", "Remain"],
  ["stem", "Flower stalk"],
  ["step", "Stair unit"],
  ["stir", "Mix with a spoon"],
  ["stop", "Red-light order"],
  ["such", "Of that kind"],
  ["suit", "Formal wear"],
  ["sure", "Certain"],
  ["swan", "Graceful swimmer"],
  ["swim", "Pool activity"],
  ["tail", "Dog's wagger"],
  ["take", "Grab"],
  ["tale", "Story"],
  ["talk", "Converse"],
  ["tall", "Skyscraper-like"],
  ["tame", "Not wild"],
  ["tape", "Sticky roll"],
  ["task", "To-do item"],
  ["team", "Group of players"],
  ["tear", "Rip"],
  ["tell", "Narrate"],
  ["tent", "Camper's shelter"],
  ["test", "Pop quiz"],
  ["than", "Comparison word"],
  ["them", "Those people"],
  ["then", "At that time"],
  ["thin", "Paper-like"],
  ["this", "The one here"],
  ["tide", "Ocean rhythm"],
  ["time", "What clocks keep"],
  ["tiny", "Very small"],
  ["toad", "Warty hopper"],
  ["tone", "Voice quality"],
  ["tool", "Hammer or saw"],
  ["torn", "Ripped"],
  ["tour", "Guided trip"],
  ["town", "Small city"],
  ["tray", "Cafeteria carrier"],
  ["tree", "Trunk owner"],
  ["trip", "Journey"],
  ["true", "Not false"],
  ["tube", "Toothpaste holder"],
  ["tune", "Melody"],
  ["turn", "Rotate"],
  ["twin", "Identical sibling"],
  ["unit", "Single measure"],
  ["upon", "Once ___ a time"],
  ["used", "Second-hand"],
  ["user", "App operator"],
  ["vase", "Flower holder"],
  ["very", "Extremely"],
  ["vest", "Sleeveless layer"],
  ["view", "Scenic sight"],
  ["vine", "Grape's climber"],
  ["vote", "Ballot action"],
  ["wait", "Stand by"],
  ["walk", "Go on foot"],
  ["wall", "Picture hanger"],
  ["warm", "Cozy"],
  ["wash", "Clean up"],
  ["wave", "Ocean roller"],
  ["wear", "Have on"],
  ["week", "Seven days"],
  ["well", "Wishing spot"],
  ["west", "Sunset direction"],
  ["what", "Which thing"],
  ["when", "At which time"],
  ["wide", "Broad"],
  ["wind", "Kite's engine"],
  ["wine", "Grape drink"],
  ["wing", "Plane part"],
  ["wire", "Electric strand"],
  ["wise", "Owl-like"],
  ["wish", "Birthday-candle act"],
  ["wolf", "Pack howler"],
  ["wood", "Lumber"],
  ["wool", "Sheep's gift"],
  ["word", "Dictionary entry"],
  ["work", "Nine-to-five"],
  ["worm", "Early bird's prize"],
  ["wrap", "Gift cover"],
  ["yard", "Three feet"],
  ["yarn", "Knitter's supply"],
  ["year", "Twelve months"],
  ["zero", "Nothing"],
  ["zone", "Designated area"]
];

export const WORDS5: readonly Entry[] = [
  ["about", "Concerning"],
  ["above", "Overhead"],
  ["actor", "Film performer"],
  ["adapt", "Adjust to change"],
  ["admit", "Confess"],
  ["adore", "Love dearly"],
  ["after", "Following"],
  ["again", "One more time"],
  ["agent", "Spy, e.g."],
  ["agree", "See eye to eye"],
  ["alarm", "Morning buzzer"],
  ["alert", "On guard"],
  ["alike", "Similar"],
  ["alive", "Breathing"],
  ["allow", "Permit"],
  ["alone", "Solo"],
  ["along", "Together with"],
  ["amber", "Fossil resin"],
  ["angel", "Halo wearer"],
  ["angle", "Protractor measure"],
  ["ankle", "Foot joint"],
  ["apart", "Separated"],
  ["apple", "Orchard classic"],
  ["apron", "Cook's cover"],
  ["arena", "Sports venue"],
  ["arise", "Get up"],
  ["armor", "Knight's suit"],
  ["aroma", "Pleasant smell"],
  ["asset", "Valuable holding"],
  ["avoid", "Steer clear of"],
  ["awake", "Not sleeping"],
  ["award", "Trophy"],
  ["badge", "Officer's shield"],
  ["baker", "Bread maker"],
  ["basic", "Fundamental"],
  ["basin", "Wash bowl"],
  ["beach", "Sandy shore"],
  ["beard", "Chin cover"],
  ["began", "Started"],
  ["begin", "Start"],
  ["being", "Existence"],
  ["below", "Underneath"],
  ["bench", "Park seat"],
  ["berry", "Small fruit"],
  ["birth", "Beginning of life"],
  ["black", "Midnight shade"],
  ["blade", "Knife edge"],
  ["blame", "Point fingers at"],
  ["blank", "Empty space"],
  ["blaze", "Roaring fire"],
  ["blend", "Smoothie action"],
  ["block", "City square"],
  ["bloom", "Flower's opening"],
  ["board", "Chess surface"],
  ["brain", "Thinking organ"],
  ["brave", "Fearless"],
  ["bread", "Sandwich essential"],
  ["break", "Recess"],
  ["brick", "Wall unit"],
  ["bride", "Aisle walker"],
  ["brief", "Short"],
  ["bring", "Carry over"],
  ["broad", "Wide"],
  ["brook", "Small stream"],
  ["broom", "Sweeper"],
  ["brown", "Chocolate shade"],
  ["brush", "Painter's tool"],
  ["build", "Construct"],
  ["cabin", "Log house"],
  ["cable", "TV wire"],
  ["camel", "Desert hauler"],
  ["candy", "Sweet treat"],
  ["canoe", "Paddled boat"],
  ["cargo", "Ship's load"],
  ["carry", "Tote"],
  ["catch", "Snag"],
  ["cause", "Reason"],
  ["chain", "Linked metal"],
  ["chair", "Table partner"],
  ["chalk", "Blackboard stick"],
  ["charm", "Bracelet dangler"],
  ["chase", "Run after"],
  ["cheap", "Bargain-priced"],
  ["check", "Restaurant bill"],
  ["chess", "Board game of kings"],
  ["chest", "Treasure box"],
  ["chief", "Leader"],
  ["child", "Youngster"],
  ["chill", "Relax"],
  ["choir", "Singing group"],
  ["civic", "Of the city"],
  ["claim", "Assert"],
  ["class", "School session"],
  ["clean", "Spotless"],
  ["clear", "Cloudless"],
  ["clerk", "Store worker"],
  ["cliff", "Sheer drop"],
  ["climb", "Scale"],
  ["clock", "Time teller"],
  ["close", "Nearby"],
  ["cloth", "Fabric"],
  ["cloud", "Sky fluff"],
  ["clown", "Circus jester"],
  ["coach", "Team leader"],
  ["coast", "Shoreline"],
  ["cocoa", "Hot winter drink"],
  ["color", "Crayon feature"],
  ["comet", "Tailed sky visitor"],
  ["coral", "Reef builder"],
  ["couch", "Living-room lounger"],
  ["count", "Tally"],
  ["court", "Tennis venue"],
  ["cover", "Book front"],
  ["crack", "Sidewalk flaw"],
  ["craft", "Handmade art"],
  ["crane", "Construction bird"],
  ["crash", "Cymbal sound"],
  ["cream", "Coffee lightener"],
  ["crime", "Detective's case"],
  ["crisp", "Fresh-lettuce quality"],
  ["cross", "Go over"],
  ["crowd", "Packed audience"],
  ["crown", "Royal headgear"],
  ["curve", "Road bend"],
  ["cycle", "Repeat loop"],
  ["daily", "Every day"],
  ["dairy", "Milk products"],
  ["dance", "Ballroom activity"],
  ["depth", "How deep"],
  ["diary", "Private journal"],
  ["dirty", "Needing a wash"],
  ["dozen", "Twelve"],
  ["draft", "Rough version"],
  ["drain", "Sink exit"],
  ["drama", "Stage genre"],
  ["dream", "Sleep story"],
  ["dress", "Gown"],
  ["drift", "Float along"],
  ["drink", "Beverage"],
  ["drive", "Take the wheel"],
  ["eagle", "Soaring raptor"],
  ["early", "Before the bell"],
  ["earth", "Third planet"],
  ["eight", "Octopus arm count"],
  ["elbow", "Arm joint"],
  ["empty", "Nothing inside"],
  ["enemy", "Foe"],
  ["enjoy", "Take pleasure in"],
  ["enter", "Go in"],
  ["equal", "The same"],
  ["error", "Mistake"],
  ["event", "Calendar entry"],
  ["every", "Each one"],
  ["exact", "Precise"],
  ["extra", "More than needed"],
  ["fable", "Moral tale"],
  ["faith", "Belief"],
  ["false", "Not true"],
  ["fancy", "Elaborate"],
  ["fever", "High temperature"],
  ["field", "Open ground"],
  ["fifty", "Half of a hundred"],
  ["final", "Last"],
  ["first", "Number one"],
  ["flame", "Candle top"],
  ["flash", "Camera burst"],
  ["fleet", "Group of ships"],
  ["float", "Stay on top of water"],
  ["floor", "What you stand on"],
  ["flour", "Baking powder base"],
  ["fluid", "Liquid"],
  ["flute", "Woodwind instrument"],
  ["focus", "Camera adjustment"],
  ["force", "Push power"],
  ["forty", "Four tens"],
  ["found", "No longer lost"],
  ["frame", "Picture border"],
  ["fresh", "Just picked"],
  ["front", "Facing side"],
  ["frost", "Cold-morning coating"],
  ["fruit", "Orchard produce"],
  ["giant", "Beanstalk dweller"],
  ["glass", "Window pane"],
  ["globe", "World model"],
  ["glory", "Fame and honour"],
  ["glove", "Hand warmer"],
  ["grace", "Elegance"],
  ["grade", "Report-card mark"],
  ["grain", "Wheat kernel"],
  ["grand", "Magnificent"],
  ["grape", "Vine fruit"],
  ["grass", "Lawn green"],
  ["great", "Excellent"],
  ["green", "Go-light colour"],
  ["greet", "Say hello to"],
  ["group", "Cluster"],
  ["guard", "Protector"],
  ["guess", "Estimate"],
  ["guest", "Visitor"],
  ["guide", "Tour leader"],
  ["habit", "Routine"],
  ["happy", "Delighted"],
  ["heart", "Valentine shape"],
  ["heavy", "Hard to lift"],
  ["hello", "Greeting"],
  ["hobby", "Free-time pursuit"],
  ["honey", "Bee product"],
  ["horse", "Stable dweller"],
  ["hotel", "Traveler's stop"],
  ["house", "Family dwelling"],
  ["human", "Person"],
  ["humor", "Comedy quality"],
  ["hurry", "Rush"],
  ["ideal", "Perfect"],
  ["image", "Picture"],
  ["index", "Back-of-book list"],
  ["inner", "Inside"],
  ["issue", "Magazine edition"],
  ["ivory", "Piano-key material"],
  ["judge", "Gavel wielder"],
  ["juice", "Breakfast drink"],
  ["knife", "Cutting utensil"],
  ["label", "Name tag"],
  ["large", "Big"],
  ["laser", "Focused beam"],
  ["laugh", "Joke response"],
  ["layer", "Cake level"],
  ["learn", "Gain knowledge"],
  ["lemon", "Sour fruit"],
  ["level", "Flat and even"],
  ["light", "Lamp output"],
  ["limit", "Maximum allowed"],
  ["local", "Neighbourhood-based"],
  ["logic", "Puzzle solver's tool"],
  ["loyal", "Faithful"],
  ["lucky", "Charmed"],
  ["lunch", "Midday meal"],
  ["magic", "Wizard's craft"],
  ["major", "Very important"],
  ["maple", "Syrup tree"],
  ["march", "Parade walk"],
  ["match", "Fire starter"],
  ["medal", "Olympic prize"],
  ["metal", "Iron or gold"],
  ["might", "Strength"],
  ["minor", "Small-scale"],
  ["minus", "Subtraction word"],
  ["model", "Small-scale replica"],
  ["money", "Wallet filler"],
  ["month", "Calendar page"],
  ["moral", "Fable's lesson"],
  ["motor", "Engine"],
  ["mount", "Climb onto"],
  ["mouse", "Cursor mover"],
  ["mouth", "River's end"],
  ["movie", "Cinema feature"],
  ["music", "Concert offering"],
  ["never", "Not ever"],
  ["night", "Owl's shift"],
  ["noble", "Aristocratic"],
  ["noise", "Racket"],
  ["north", "Compass top"],
  ["novel", "Long fiction"],
  ["nurse", "Hospital helper"],
  ["ocean", "Vast blue expanse"],
  ["offer", "Propose"],
  ["often", "Frequently"],
  ["olive", "Martini garnish"],
  ["onion", "Tearful vegetable"],
  ["opera", "Grand musical drama"],
  ["orbit", "Planet's path"],
  ["order", "Restaurant request"],
  ["organ", "Church instrument"],
  ["other", "Different one"],
  ["ounce", "Small weight"],
  ["outer", "External"],
  ["owner", "Title holder"],
  ["paint", "Wall colour"],
  ["panda", "Bamboo eater"],
  ["panel", "Expert group"],
  ["paper", "Printer feed"],
  ["party", "Birthday bash"],
  ["pause", "Brief stop"],
  ["peace", "War's opposite"],
  ["pearl", "Oyster's gem"],
  ["pedal", "Bike pusher"],
  ["phone", "Pocket ringer"],
  ["photo", "Album filler"],
  ["piano", "88-key instrument"],
  ["piece", "Portion"],
  ["pilot", "Cockpit occupant"],
  ["pizza", "Slice source"],
  ["place", "Location"],
  ["plain", "Unadorned"],
  ["plane", "Airport departer"],
  ["plant", "Windowsill green"],
  ["plate", "Dinner disc"],
  ["point", "Pencil tip"],
  ["polar", "Arctic-like"],
  ["porch", "Front sitting spot"],
  ["pound", "Sixteen ounces"],
  ["power", "Electric supply"],
  ["press", "Push down"],
  ["price", "Tag number"],
  ["pride", "Lion group"],
  ["prize", "Contest reward"],
  ["proof", "Evidence"],
  ["proud", "Pleased with oneself"],
  ["pupil", "Eye center"],
  ["queen", "Chess power piece"],
  ["quick", "Speedy"],
  ["quiet", "Library rule"],
  ["radio", "Car dashboard box"],
  ["raise", "Lift up"],
  ["ranch", "Cattle spread"],
  ["range", "Mountain chain"],
  ["rapid", "Swift"],
  ["reach", "Stretch toward"],
  ["ready", "All set"],
  ["rhyme", "Poet's echo"],
  ["ridge", "Mountain crest"],
  ["right", "Correct"],
  ["river", "Bridge crosser"],
  ["roast", "Sunday dinner"],
  ["robin", "Red-breasted bird"],
  ["robot", "Mechanical helper"],
  ["rocky", "Full of stones"],
  ["round", "Circle-shaped"],
  ["route", "Planned path"],
  ["royal", "Palace resident"],
  ["rural", "Countryside-like"],
  ["salad", "Leafy starter"],
  ["salsa", "Chip dip"],
  ["scale", "Fish covering"],
  ["scene", "Play division"],
  ["scent", "Perfume trail"],
  ["score", "Game tally"],
  ["sense", "Sight or smell"],
  ["seven", "Lucky number"],
  ["shade", "Tree's gift"],
  ["shape", "Circle or square"],
  ["share", "Split evenly"],
  ["sharp", "Knife-like"],
  ["sheep", "Wool source"],
  ["shelf", "Book perch"],
  ["shell", "Beach find"],
  ["shine", "Gleam"],
  ["shirt", "Torso wear"],
  ["shore", "Water's edge"],
  ["short", "Not tall"],
  ["shout", "Yell"],
  ["sight", "One of five senses"],
  ["silly", "Goofy"],
  ["since", "From that time"],
  ["skill", "Practiced ability"],
  ["sleep", "Nightly recharge"],
  ["slice", "Pizza portion"],
  ["small", "Little"],
  ["smart", "Clever"],
  ["smile", "Camera prompt"],
  ["smoke", "Chimney output"],
  ["snack", "Between-meals bite"],
  ["snake", "Legless slitherer"],
  ["solar", "Sun-powered"],
  ["solid", "Not liquid"],
  ["solve", "Crack the puzzle"],
  ["sound", "What ears catch"],
  ["south", "Compass bottom"],
  ["space", "Astronaut's realm"],
  ["spare", "Extra tire"],
  ["speak", "Talk"],
  ["speed", "Velocity"],
  ["spice", "Cinnamon, e.g."],
  ["spoon", "Soup scooper"],
  ["sport", "Athletic pursuit"],
  ["stage", "Actor's platform"],
  ["stair", "Step"],
  ["stamp", "Envelope corner"],
  ["stand", "Rise to your feet"],
  ["start", "Begin"],
  ["state", "One of fifty"],
  ["steam", "Kettle cloud"],
  ["steel", "Skyscraper metal"],
  ["stick", "Twig"],
  ["still", "Motionless"],
  ["stone", "Small rock"],
  ["store", "Shop"],
  ["storm", "Thunder bringer"],
  ["story", "Bedtime telling"],
  ["stove", "Kitchen heater"],
  ["straw", "Drink tube"],
  ["sugar", "Sweet crystals"],
  ["sunny", "Cloudless"],
  ["super", "Excellent"],
  ["sweet", "Like candy"],
  ["table", "Dinner surface"],
  ["taste", "Tongue's sense"],
  ["teach", "Instruct"],
  ["thank", "Show gratitude"],
  ["theme", "Party motif"],
  ["there", "Not here"],
  ["thick", "Like molasses"],
  ["thing", "Object"],
  ["think", "Use your head"],
  ["third", "Bronze-medal place"],
  ["three", "Triangle sides"],
  ["throw", "Toss"],
  ["tiger", "Striped cat"],
  ["tight", "Snug"],
  ["title", "Book's name"],
  ["toast", "Breakfast slice"],
  ["today", "This very day"],
  ["token", "Arcade coin"],
  ["tooth", "Dentist's focus"],
  ["total", "Grand sum"],
  ["touch", "Make contact"],
  ["tower", "Castle spire"],
  ["trace", "Follow the outline"],
  ["track", "Runner's oval"],
  ["trade", "Swap"],
  ["trail", "Hiking path"],
  ["train", "Rail rider"],
  ["treat", "Halloween handout"],
  ["trial", "Court event"],
  ["truck", "Big hauler"],
  ["trunk", "Elephant's nose"],
  ["trust", "Have faith in"],
  ["truth", "The facts"],
  ["tulip", "Spring bulb bloom"],
  ["tutor", "Private teacher"],
  ["twice", "Two times"],
  ["uncle", "Parent's brother"],
  ["under", "Beneath"],
  ["union", "Joining together"],
  ["upper", "Higher"],
  ["urban", "City-like"],
  ["usual", "Typical"],
  ["value", "Worth"],
  ["video", "Moving pictures"],
  ["visit", "Drop by"],
  ["vital", "Essential"],
  ["voice", "Singer's instrument"],
  ["wagon", "Little red hauler"],
  ["waste", "Squander"],
  ["watch", "Wrist clock"],
  ["water", "H2O"],
  ["weigh", "Step on the scale"],
  ["whale", "Ocean giant"],
  ["wheat", "Bread grain"],
  ["wheel", "Car circle"],
  ["where", "In what place"],
  ["which", "What one"],
  ["while", "During the time"],
  ["white", "Snow shade"],
  ["whole", "Entire"],
  ["woman", "Adult female"],
  ["world", "The whole globe"],
  ["worth", "Value"],
  ["wrist", "Watch spot"],
  ["write", "Put pen to paper"],
  ["wrong", "Incorrect"],
  ["yield", "Give way"],
  ["young", "Not old"],
  ["youth", "Young years"]
];
